[WIP]Add search filter
Digital-Prophets/itez pull request #45
Opened 2021-12-07 09:08 UTC by cazterk

2021-12-07 11:00 UTC, sonlinux requested changes

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +    # print("------------------------------>", context["qs_json"])
lets remove this

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +            beneficiary = Beneficiary.objects.filter(Q(first_name__contains=q) | Q(
`Beneficiary.objects.filter(alive=True and Q(first_name__contains=q)..`

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +        #     if i.startswith(s)
lets clean this  up

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +
lets remove all commented code

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +        context["qs_json"] = export_type  # [value for value in Beneficiary.objects.values()]
lets call this `search_json_qs`

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +        return render(request, {'filter': beneficiary_filter})
this can go

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +@ login_required(login_url="/login/")
this need to be `@login_required(login_url="/login/")` and not `@ login_required(login_url="/login/")`

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +@ login_required(login_url="/login/")
same here

2021-12-07 11:00 UTC, sonlinux commented on itez/beneficiary/views.py
> +@ login_required(login_url="/login/")
do the same here

2021-12-07 11:00 UTC, sonlinux commented on itez/templates/beneficiary/beneficiary_list.html
> +                                </div>
we dont need to print suggestions on the table section 
instead they should be highlights

2021-12-07 11:00 UTC, sonlinux commented on itez/templates/beneficiary/beneficiary_list.html
> +    const data = '{{qs_json}}'
lets update this with context variable too

2021-12-07 11:00 UTC, sonlinux commented on itez/templates/beneficiary/beneficiary_list.html
> +          box.innerHTML += `<b> ${info['first_name']}  ${info['last_name']}</b><br>`
we need to include `beneficiary ID` too

2021-12-07 11:00 UTC, sonlinux commented on requirements/base.txt
>  # Common
leave a space below here

2021-12-07 11:48 UTC, cazterk commented on itez/beneficiary/views.py
> +    # print("------------------------------>", context["qs_json"])
- [x] remove commented code

2021-12-07 11:48 UTC, cazterk commented on itez/beneficiary/views.py
> +            beneficiary = Beneficiary.objects.filter(Q(first_name__contains=q) | Q(
- [x] add alive condition

2021-12-07 11:51 UTC, cazterk commented on itez/beneficiary/views.py
> +        #     if i.startswith(s)
- [x] remove commented code

2021-12-07 11:51 UTC, cazterk commented on itez/beneficiary/views.py
> +
- [x] remove commented code

2021-12-07 11:54 UTC, cazterk commented on itez/beneficiary/views.py
> +        return render(request, {'filter': beneficiary_filter})
- [x] remove redundant code

2021-12-07 11:56 UTC, cazterk commented on itez/beneficiary/views.py
> +        context["qs_json"] = export_type  # [value for value in Beneficiary.objects.values()]
- [x] 'qs-json' => 'search_json_qs'

2021-12-07 11:57 UTC, cazterk commented on itez/beneficiary/views.py
> +@ login_required(login_url="/login/")
- [x] delete initial space

2021-12-07 11:58 UTC, cazterk commented on itez/beneficiary/views.py
> +@ login_required(login_url="/login/")
- [x] delete initial space

2021-12-07 11:58 UTC, cazterk commented on itez/beneficiary/views.py
> +@ login_required(login_url="/login/")
- [x] delete initial space

2021-12-07 11:59 UTC, cazterk commented on requirements/base.txt
>  # Common
- [x] leave space

2021-12-07 12:25 UTC, cazterk commented on itez/templates/beneficiary/beneficiary_list.html
> +          box.innerHTML += `<b> ${info['first_name']}  ${info['last_name']}</b><br>`
- [x] add beneficiary_id

2021-12-07 12:25 UTC, cazterk commented on itez/templates/beneficiary/beneficiary_list.html
> +    const data = '{{qs_json}}'
- [x] update context

2021-12-07 13:46 UTC, cazterk commented on itez/templates/beneficiary/beneficiary_list.html
> +                                </div>
- [x] remove print suggections

2021-12-08 09:45 UTC, sonlinux approved these changes

2021-12-08 09:45 UTC, merged